// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UgovorOZakupuService.Entities;

namespace UgovorOZakupuService.Migrations
{
    [DbContext(typeof(UgovorContext))]
    [Migration("20220217144440_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UgovorOZakupuService.Entities.Dokument", b =>
                {
                    b.Property<Guid>("DokumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumDonosenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sablon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZavodniBrojD")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DokumentID");

                    b.ToTable("Dokument");

                    b.HasData(
                        new
                        {
                            DokumentID = new Guid("6d9bf251-8c70-495f-93bf-ff1e9ad85b88"),
                            Datum = new DateTime(2020, 3, 22, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumDonosenja = new DateTime(2020, 3, 22, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Sablon = "Rešenje o obrazovanju stručne komisije za izradu predloga godišnjeg Programa zaštite, uređenja i korišćenja poljoprivrednog zemljišta",
                            ZavodniBrojD = "ROO-1/17"
                        },
                        new
                        {
                            DokumentID = new Guid("6e5dff7a-ea13-4294-8f95-5f258e32f96f"),
                            Datum = new DateTime(2019, 9, 15, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            DatumDonosenja = new DateTime(2019, 9, 15, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Sablon = "Rešenje o obrazovanju komisije za davanje mišljenja na godišnji Program zaštite, uređenja i korišćenja poljoprivrednog zemljišta",
                            ZavodniBrojD = "ROO-2/17"
                        },
                        new
                        {
                            DokumentID = new Guid("38d906b5-f8d5-4775-b0a1-1edee955193f"),
                            Datum = new DateTime(2021, 4, 12, 13, 22, 31, 0, DateTimeKind.Unspecified),
                            DatumDonosenja = new DateTime(2021, 4, 12, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Sablon = "Zahtev za davanje saglasnosti na godišnji Program zaštite, uređenja i korišćenja poljoprivrednog zemljišta",
                            ZavodniBrojD = "ZDS-5/10"
                        },
                        new
                        {
                            DokumentID = new Guid("4a807a16-a73f-4f02-944a-0db26fd2fa5e"),
                            Datum = new DateTime(2020, 2, 18, 10, 29, 41, 0, DateTimeKind.Unspecified),
                            DatumDonosenja = new DateTime(2020, 3, 1, 12, 44, 51, 0, DateTimeKind.Unspecified),
                            Sablon = "Program zaštite, uređenja i korišćenja poljopriverednog zemljišta",
                            ZavodniBrojD = "PZU-3/11"
                        },
                        new
                        {
                            DokumentID = new Guid("f80153c4-322b-4eee-b73f-cd450fa8c1cd"),
                            Datum = new DateTime(2020, 9, 12, 15, 12, 11, 0, DateTimeKind.Unspecified),
                            DatumDonosenja = new DateTime(2020, 11, 5, 12, 0, 51, 0, DateTimeKind.Unspecified),
                            Sablon = "Odluka o određivanju nadležnog organa za sprovođenje postupaka davanja poljoprivrednog zemljišta u zakup",
                            ZavodniBrojD = "ONO-4/14"
                        },
                        new
                        {
                            DokumentID = new Guid("af511cdf-cd94-400a-815e-2bf5b329eff2"),
                            Datum = new DateTime(2021, 6, 10, 14, 34, 15, 0, DateTimeKind.Unspecified),
                            DatumDonosenja = new DateTime(2021, 8, 5, 13, 2, 50, 0, DateTimeKind.Unspecified),
                            Sablon = "Rešenje o obrazovanju Komisije za sprovođenje postupaka davanje poljoprivrednog zemljišta u zakup",
                            ZavodniBrojD = "ROK-7/19"
                        },
                        new
                        {
                            DokumentID = new Guid("cb41cfed-1d43-4f45-8971-a91fd9f144a7"),
                            Datum = new DateTime(2022, 1, 30, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            DatumDonosenja = new DateTime(2022, 2, 5, 12, 0, 12, 0, DateTimeKind.Unspecified),
                            Sablon = "Predlog odluke o raspisivanju javnog oglasa za davanje u zakup poljoprivrednog zemljišta u državnoj svojini",
                            ZavodniBrojD = "POD-7/10"
                        },
                        new
                        {
                            DokumentID = new Guid("2f1c2288-8255-4128-aa44-91303617bcb8"),
                            Datum = new DateTime(2020, 3, 25, 8, 35, 23, 0, DateTimeKind.Unspecified),
                            DatumDonosenja = new DateTime(2020, 4, 15, 13, 11, 23, 0, DateTimeKind.Unspecified),
                            Sablon = "Odluka o raspisivanju javnog oglasa za davanje u zakup poljoprivrednog zemljišta u državnoj svojini",
                            ZavodniBrojD = "ONO-4/14"
                        });
                });

            modelBuilder.Entity("UgovorOZakupuService.Entities.Rok", b =>
                {
                    b.Property<Guid>("RokID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumRokaDospeca")
                        .HasColumnType("datetime2");

                    b.HasKey("RokID");

                    b.ToTable("Rok");

                    b.HasData(
                        new
                        {
                            RokID = new Guid("34562293-3bb6-4ef3-922f-f9d7d3c57864"),
                            DatumRokaDospeca = new DateTime(2021, 3, 22, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("UgovorOZakupuService.Entities.TipGarancije", b =>
                {
                    b.Property<Guid>("TipGarancijeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivTipaG")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipGarancijeID");

                    b.ToTable("TipGarancije");

                    b.HasData(
                        new
                        {
                            TipGarancijeID = new Guid("8a02b3ef-651c-4893-8c71-8cf5ca4619fe"),
                            NazivTipaG = "Jemstvo"
                        },
                        new
                        {
                            TipGarancijeID = new Guid("d2e52d2e-8c27-49e1-b4e0-4a873a6ca75e"),
                            NazivTipaG = "Bankarska Garancija"
                        },
                        new
                        {
                            TipGarancijeID = new Guid("8d66093b-bffa-4b50-8d94-f1a9dd9a336c"),
                            NazivTipaG = "Garancija nekretninom"
                        },
                        new
                        {
                            TipGarancijeID = new Guid("311eafc9-251d-40ee-835d-d40cedf96caf"),
                            NazivTipaG = "Žirantska"
                        },
                        new
                        {
                            TipGarancijeID = new Guid("14df6d32-8cf8-4516-975d-cbf6f63889ff"),
                            NazivTipaG = "Uplata gotovinom"
                        });
                });

            modelBuilder.Entity("UgovorOZakupuService.Entities.Ugovor", b =>
                {
                    b.Property<Guid>("UgovorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumPotpisa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumZavodjenja")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DokumentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("JavnoNadmetanjeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KorisnikID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KupacID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LicnostID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MestoPotpisivanja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RokID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RokZaVracanjeZem")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TipGarancijeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZavodniBroj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UgovorID");

                    b.ToTable("Ugovor");

                    b.HasData(
                        new
                        {
                            UgovorID = new Guid("0ec914e2-a7a2-4935-ad30-5912fc86fd19"),
                            DatumPotpisa = new DateTime(2022, 1, 23, 14, 20, 57, 0, DateTimeKind.Unspecified),
                            DatumZavodjenja = new DateTime(2022, 1, 18, 16, 14, 33, 0, DateTimeKind.Unspecified),
                            DokumentID = new Guid("f00355a8-b3dc-4a6f-b4d7-46f4d7d7a9c7"),
                            JavnoNadmetanjeID = new Guid("84b3ea4c-e02f-41b1-a1ef-2734ef97abb2"),
                            KorisnikID = new Guid("25862727-de11-49c4-aea2-5431db48f0a5"),
                            KupacID = new Guid("81037b57-d24c-4d85-9649-7fc6ed635a0c"),
                            LicnostID = new Guid("45aed467-8061-4011-bfc6-3bc4d01b65f9"),
                            MestoPotpisivanja = "Beograd",
                            RokID = new Guid("8d6b2975-80bc-4823-9216-66cc6892d29e"),
                            RokZaVracanjeZem = new DateTime(2023, 4, 29, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TipGarancijeID = new Guid("f5c2bfbf-06e0-4a11-9b05-e7940d146016"),
                            ZavodniBroj = "UGV-3/21"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
