// <auto-generated />
using System;
using KupacService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KupacService.Migrations
{
    [DbContext(typeof(KupacContext))]
    [Migration("20220221114410_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KupacService.Entities.Kupac", b =>
                {
                    b.Property<Guid>("KupacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumPocetkaZabrane")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPrestankaZabrane")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatumTrajanjaZabrane")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ImaZabranu")
                        .HasColumnType("bit");

                    b.Property<string>("OstvarenaPovrsina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OvlascenoLiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PrioritetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KupacId");

                    b.ToTable("Kupac");

                    b.HasData(
                        new
                        {
                            KupacId = new Guid("a35d8ec7-4cea-42ec-859e-5c012476ced0"),
                            DatumPocetkaZabrane = new DateTime(2020, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumPrestankaZabrane = new DateTime(2021, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumTrajanjaZabrane = "1 godinu",
                            ImaZabranu = true,
                            OstvarenaPovrsina = "200m2",
                            OvlascenoLiceId = new Guid("148805f4-3093-4fd3-aea1-f253038b3c8f"),
                            PrioritetId = new Guid("608ed376-c4bb-4bdd-84cb-f34147ca96df")
                        });
                });

            modelBuilder.Entity("KupacService.Entities.NajboljiPonudjac", b =>
                {
                    b.Property<Guid>("NajboljiPonudjacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KupacId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NajboljiPonudjacId");

                    b.ToTable("Najbolji_Ponudjac");

                    b.HasData(
                        new
                        {
                            NajboljiPonudjacId = new Guid("c566ecfd-a27d-4a0b-8032-66fc24754929"),
                            KupacId = new Guid("a35d8ec7-4cea-42ec-859e-5c012476ced0")
                        });
                });

            modelBuilder.Entity("KupacService.Entities.PrijavljenKupac", b =>
                {
                    b.Property<Guid>("PrijavljenKupacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KupacId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PrijavljenKupacId");

                    b.ToTable("Prijavljen_Kupac");

                    b.HasData(
                        new
                        {
                            PrijavljenKupacId = new Guid("1a1bdf95-8ee1-4998-a78c-360039502626"),
                            KupacId = new Guid("a35d8ec7-4cea-42ec-859e-5c012476ced0")
                        });
                });

            modelBuilder.Entity("KupacService.Entities.Prioritet", b =>
                {
                    b.Property<Guid>("PrioritetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivPrioriteta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrioritetId");

                    b.ToTable("Prioritet");

                    b.HasData(
                        new
                        {
                            PrioritetId = new Guid("20e00a61-9e6a-4d6b-9df0-0b85e645849d"),
                            NazivPrioriteta = "Prioritet1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
