// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UplataService.Entities;

namespace UplataService.Migrations
{
    [DbContext(typeof(UplataContext))]
    [Migration("20220217184703_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UplataService.Entities.Uplata", b =>
                {
                    b.Property<Guid>("UplataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Broj_Racuna")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumKursa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumUplate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Iznos")
                        .HasColumnType("int");

                    b.Property<int>("Poziv_Na_Broj")
                        .HasColumnType("int");

                    b.Property<string>("Svrha_Uplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valuta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Vrednost")
                        .HasColumnType("real");

                    b.HasKey("UplataID");

                    b.ToTable("Uplata");

                    b.HasData(
                        new
                        {
                            UplataID = new Guid("44af7348-2f6c-7763-84c7-0d3ddf556dde"),
                            Broj_Racuna = 289451,
                            DatumKursa = new DateTime(2021, 1, 1, 10, 3, 0, 0, DateTimeKind.Unspecified),
                            DatumUplate = new DateTime(2021, 1, 1, 10, 3, 0, 0, DateTimeKind.Unspecified),
                            Iznos = 2584,
                            Poziv_Na_Broj = 54185612,
                            Svrha_Uplate = "Uplata javnog nadmetanja",
                            Valuta = "RSD",
                            Vrednost = 2584f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
