// <auto-generated />
using System;
using LiceService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LiceService.Migrations
{
    [DbContext(typeof(LiceContext))]
    partial class LiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LiceService.Entities.FizickoLice", b =>
                {
                    b.Property<Guid>("LiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("JMBG")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LiceID");

                    b.ToTable("FizickoLice");

                    b.HasData(
                        new
                        {
                            LiceID = new Guid("8de0c01b-b7b0-4df2-9009-3df21b91a0bb"),
                            Ime = "Marko",
                            JMBG = new Guid("18dca15b-188f-49f9-b4db-ece15575995a"),
                            Prezime = "Markovic"
                        });
                });

            modelBuilder.Entity("LiceService.Entities.KontaktOsoba", b =>
                {
                    b.Property<Guid>("KontaktOsobaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Funkcija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Maticni_Broj")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KontaktOsobaID");

                    b.ToTable("KontaktOsoba");

                    b.HasData(
                        new
                        {
                            KontaktOsobaID = new Guid("a43a31f7-ffad-4aff-a199-1a6d31a8b850"),
                            Funkcija = "Generalni direktor",
                            Ime = "Petar",
                            Maticni_Broj = new Guid("ffc4407f-68a8-4d74-a48d-17389cc3f01f"),
                            Prezime = "Petrovic",
                            Telefon = "0658899471"
                        });
                });

            modelBuilder.Entity("LiceService.Entities.Lice", b =>
                {
                    b.Property<Guid>("LiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Broj_Racuna")
                        .HasColumnType("int");

                    b.Property<int>("Broj_Telefona1")
                        .HasColumnType("int");

                    b.Property<int>("Broj_Telefona2")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LiceID");

                    b.ToTable("Lice");

                    b.HasData(
                        new
                        {
                            LiceID = new Guid("8de0c01b-b7b0-4df2-9009-3df21b91a0bb"),
                            Broj_Racuna = 123456789,
                            Broj_Telefona1 = 654488522,
                            Broj_Telefona2 = 654488521,
                            Email = "nekolice@gmail.com"
                        },
                        new
                        {
                            LiceID = new Guid("e7c1316d-5805-4d2b-be96-f764f0247acc"),
                            Broj_Racuna = 987456123,
                            Broj_Telefona1 = 614188522,
                            Broj_Telefona2 = 624489521,
                            Email = "nekolice99@gmail.com"
                        });
                });

            modelBuilder.Entity("LiceService.Entities.PravnoLice", b =>
                {
                    b.Property<Guid>("LiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MaticniBroj")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LiceID");

                    b.ToTable("PravnoLice");

                    b.HasData(
                        new
                        {
                            LiceID = new Guid("e7c1316d-5805-4d2b-be96-f764f0247acc"),
                            MaticniBroj = new Guid("ffc4407f-68a8-4d74-a48d-17389cc3f01f"),
                            Naziv = "Firma1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
