// <auto-generated />
using System;
using JavnoNadmetanjeService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JavnoNadmetanjeService.Migrations
{
    [DbContext(typeof(JavnoNadmetanjeContext))]
    [Migration("20220211164112_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JavnoNadmetanjeService.Entities.JavnoNadmetanje", b =>
                {
                    b.Property<Guid>("JavnoNadmetanjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrojUcesnika")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("IzlicitiranaCena")
                        .HasColumnType("int");

                    b.Property<bool>("Izuzeto")
                        .HasColumnType("bit");

                    b.Property<Guid>("KatastarskaOpstinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Krug")
                        .HasColumnType("int");

                    b.Property<int>("PeriodZakupa")
                        .HasColumnType("int");

                    b.Property<int>("PocetnaCenaHektar")
                        .HasColumnType("int");

                    b.Property<Guid>("StatusJavnogNadmetanjaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipJavnogNadmetanjaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VisinaDopuneDepozita")
                        .HasColumnType("int");

                    b.Property<DateTime>("VremeKraja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremePocetka")
                        .HasColumnType("datetime2");

                    b.HasKey("JavnoNadmetanjeId");

                    b.HasIndex("KatastarskaOpstinaId");

                    b.HasIndex("StatusJavnogNadmetanjaId");

                    b.HasIndex("TipJavnogNadmetanjaId");

                    b.ToTable("JavnoNadmetanje");

                    b.HasData(
                        new
                        {
                            JavnoNadmetanjeId = new Guid("1ae8137b-1674-4c91-a4b5-87a133f5dd87"),
                            BrojUcesnika = 15,
                            Datum = new DateTime(2022, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IzlicitiranaCena = 8600,
                            Izuzeto = false,
                            KatastarskaOpstinaId = new Guid("24742b99-32c6-4999-b0a7-757a178f9ee7"),
                            Krug = 1,
                            PeriodZakupa = 12,
                            PocetnaCenaHektar = 7000,
                            StatusJavnogNadmetanjaId = new Guid("167a01c0-2e68-46a8-b201-3a23e3a20bff"),
                            TipJavnogNadmetanjaId = new Guid("bc679089-e19f-43e4-946f-651ffbdb2afb"),
                            VisinaDopuneDepozita = 200,
                            VremeKraja = new DateTime(2022, 2, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            VremePocetka = new DateTime(2022, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("JavnoNadmetanjeService.Entities.KatastarskaOpstina", b =>
                {
                    b.Property<Guid>("KatastarskaOpstinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivKatastarskeOpstine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KatastarskaOpstinaId");

                    b.ToTable("KatastarskaOpstina");

                    b.HasData(
                        new
                        {
                            KatastarskaOpstinaId = new Guid("7d03a946-40a3-41e8-8feb-dbe9381d2170"),
                            NazivKatastarskeOpstine = "Čantavir"
                        },
                        new
                        {
                            KatastarskaOpstinaId = new Guid("5a20c276-5b98-4e24-92b4-0996cb51b293"),
                            NazivKatastarskeOpstine = "Bački Vinogradi"
                        },
                        new
                        {
                            KatastarskaOpstinaId = new Guid("24742b99-32c6-4999-b0a7-757a178f9ee7"),
                            NazivKatastarskeOpstine = "Bikovo"
                        },
                        new
                        {
                            KatastarskaOpstinaId = new Guid("55c5e423-e70c-452f-a89f-42c412163b76"),
                            NazivKatastarskeOpstine = "Đuđin"
                        },
                        new
                        {
                            KatastarskaOpstinaId = new Guid("714f831b-b86b-443d-abf5-f248694a8b2e"),
                            NazivKatastarskeOpstine = "Žednik"
                        },
                        new
                        {
                            KatastarskaOpstinaId = new Guid("835bd51d-80e3-4c28-9e34-3951bac861c7"),
                            NazivKatastarskeOpstine = "Tavankut"
                        },
                        new
                        {
                            KatastarskaOpstinaId = new Guid("ddc12930-390b-4e16-8c91-b9259d53bf16"),
                            NazivKatastarskeOpstine = "Bajmok"
                        },
                        new
                        {
                            KatastarskaOpstinaId = new Guid("a077a57d-6e63-41c8-a944-c93eb938b8f7"),
                            NazivKatastarskeOpstine = "Donji Grad"
                        },
                        new
                        {
                            KatastarskaOpstinaId = new Guid("26831746-3efb-48a5-8cd9-9810db3a75f4"),
                            NazivKatastarskeOpstine = "Stari Grad"
                        },
                        new
                        {
                            KatastarskaOpstinaId = new Guid("f0152fa7-8abc-43e9-956d-1eff5a4ace62"),
                            NazivKatastarskeOpstine = "Novi Grad"
                        },
                        new
                        {
                            KatastarskaOpstinaId = new Guid("870742be-2358-45f2-bb1b-1d4efa6bf9d2"),
                            NazivKatastarskeOpstine = "Palić"
                        });
                });

            modelBuilder.Entity("JavnoNadmetanjeService.Entities.SluzbeniList", b =>
                {
                    b.Property<Guid>("SluzbeniListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojSluzbenogLista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JavnoNadmetanjeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Opstina")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SluzbeniListId");

                    b.HasIndex("JavnoNadmetanjeId");

                    b.ToTable("SluzbeniList");

                    b.HasData(
                        new
                        {
                            SluzbeniListId = new Guid("496ac934-a718-43a6-ac7f-8db141478180"),
                            BrojSluzbenogLista = "5/2022",
                            DatumIzdavanja = new DateTime(2022, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JavnoNadmetanjeId = new Guid("1ae8137b-1674-4c91-a4b5-87a133f5dd87"),
                            Opstina = "Bikovo"
                        });
                });

            modelBuilder.Entity("JavnoNadmetanjeService.Entities.StatusJavnogNadmetanja", b =>
                {
                    b.Property<Guid>("StatusJavnogNadmetanjaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivStatusaJavnogNadmetanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusJavnogNadmetanjaId");

                    b.ToTable("StatusJavnogNadmetanja");

                    b.HasData(
                        new
                        {
                            StatusJavnogNadmetanjaId = new Guid("167a01c0-2e68-46a8-b201-3a23e3a20bff"),
                            NazivStatusaJavnogNadmetanja = "Prvi krug"
                        },
                        new
                        {
                            StatusJavnogNadmetanjaId = new Guid("f876fbcc-a7d0-49f8-b6ef-9b5a59c44fa0"),
                            NazivStatusaJavnogNadmetanja = "Drugi krug sa starim uslovima"
                        },
                        new
                        {
                            StatusJavnogNadmetanjaId = new Guid("cb5b3279-811c-4ca4-abaa-69016ba157b6"),
                            NazivStatusaJavnogNadmetanja = "Drugi krug sa novim uslovima"
                        });
                });

            modelBuilder.Entity("JavnoNadmetanjeService.Entities.TipJavnogNadmetanja", b =>
                {
                    b.Property<Guid>("TipJavnogNadmetanjaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivTipaJavnogNadmetanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipJavnogNadmetanjaId");

                    b.ToTable("TipJavnogNadmetanja");

                    b.HasData(
                        new
                        {
                            TipJavnogNadmetanjaId = new Guid("bc679089-e19f-43e4-946f-651ffbdb2afb"),
                            NazivTipaJavnogNadmetanja = "Javna licitacija"
                        },
                        new
                        {
                            TipJavnogNadmetanjaId = new Guid("d7a80343-d802-43d6-b128-79ba8554acd2"),
                            NazivTipaJavnogNadmetanja = "Otvaranje zatvorenih ponuda"
                        });
                });

            modelBuilder.Entity("JavnoNadmetanjeService.Entities.JavnoNadmetanje", b =>
                {
                    b.HasOne("JavnoNadmetanjeService.Entities.KatastarskaOpstina", "KatastarskaOpstina")
                        .WithMany("JavnoNadmetanjeList")
                        .HasForeignKey("KatastarskaOpstinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JavnoNadmetanjeService.Entities.StatusJavnogNadmetanja", "StatusJavnogNadmetanja")
                        .WithMany("JavnoNadmetanjeList")
                        .HasForeignKey("StatusJavnogNadmetanjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JavnoNadmetanjeService.Entities.TipJavnogNadmetanja", "TipJavnogNadmetanja")
                        .WithMany("JavnoNadmetanjeList")
                        .HasForeignKey("TipJavnogNadmetanjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JavnoNadmetanjeService.Entities.SluzbeniList", b =>
                {
                    b.HasOne("JavnoNadmetanjeService.Entities.JavnoNadmetanje", "JavnoNadmetanje")
                        .WithMany("SluzbeniListList")
                        .HasForeignKey("JavnoNadmetanjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
