// <auto-generated />
using System;
using LicitacijaService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LicitacijaService.Migrations
{
    [DbContext(typeof(LicitacijaContext))]
    [Migration("20220216173557_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LicitacijaService.Entities.Dokumentacija", b =>
                {
                    b.Property<Guid>("DokumentacijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivDokumentacije")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DokumentacijaID");

                    b.ToTable("Dokumentacija");

                    b.HasData(
                        new
                        {
                            DokumentacijaID = new Guid("f1247d53-334e-433f-84dd-b67a3660a269"),
                            NazivDokumentacije = "Dokumentacija1"
                        },
                        new
                        {
                            DokumentacijaID = new Guid("3465e0f2-a2bd-4ef6-bcda-fa2e71488caa"),
                            NazivDokumentacije = "Dokumentacija2"
                        },
                        new
                        {
                            DokumentacijaID = new Guid("4cc35a36-46cc-4115-bc4b-a580e20cd23f"),
                            NazivDokumentacije = "Dokumentacija3"
                        },
                        new
                        {
                            DokumentacijaID = new Guid("d8695c8d-ce0f-40be-a7b4-82042c223e39"),
                            NazivDokumentacije = "Dokumentacija4"
                        });
                });

            modelBuilder.Entity("LicitacijaService.Entities.DokumentacijaZaFizickoLice", b =>
                {
                    b.Property<Guid>("DokumentacijaFlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DokumentacijaID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DokumentacijaFlID");

                    b.HasIndex("DokumentacijaID");

                    b.ToTable("DokumentacijaZaFizickoLice");

                    b.HasData(
                        new
                        {
                            DokumentacijaFlID = new Guid("050c3e3d-0698-48a3-a1c5-eda9dc448da5"),
                            DokumentacijaID = new Guid("f1247d53-334e-433f-84dd-b67a3660a269")
                        },
                        new
                        {
                            DokumentacijaFlID = new Guid("ee695aa1-7e7b-47d4-9670-541b3537c07e"),
                            DokumentacijaID = new Guid("3465e0f2-a2bd-4ef6-bcda-fa2e71488caa")
                        });
                });

            modelBuilder.Entity("LicitacijaService.Entities.DokumentacijaZaPravnoLice", b =>
                {
                    b.Property<Guid>("DokumentacijaPlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DokumentacijaID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DokumentacijaPlID");

                    b.HasIndex("DokumentacijaID");

                    b.ToTable("DokumentacijaZaPravnoLice");

                    b.HasData(
                        new
                        {
                            DokumentacijaPlID = new Guid("20e00a61-9e6a-4d6b-9df0-0b85e645849d"),
                            DokumentacijaID = new Guid("4cc35a36-46cc-4115-bc4b-a580e20cd23f")
                        },
                        new
                        {
                            DokumentacijaPlID = new Guid("71ba2ade-8528-4b22-8bd2-2b3bc1ec523c"),
                            DokumentacijaID = new Guid("d8695c8d-ce0f-40be-a7b4-82042c223e39")
                        });
                });

            modelBuilder.Entity("LicitacijaService.Entities.Licitacija", b =>
                {
                    b.Property<Guid>("LicitacijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Broj")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DokumentacijaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Godina")
                        .HasColumnType("int");

                    b.Property<string>("KorakCene")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ogranicenje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RokZaPrijavu")
                        .HasColumnType("datetime2");

                    b.HasKey("LicitacijaID");

                    b.HasIndex("DokumentacijaID");

                    b.ToTable("Licitacija");

                    b.HasData(
                        new
                        {
                            LicitacijaID = new Guid("50af7348-2f6c-4763-84c7-0d9ddf556dde"),
                            Broj = 1,
                            Datum = new DateTime(2020, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DokumentacijaID = new Guid("3465e0f2-a2bd-4ef6-bcda-fa2e71488caa"),
                            Godina = 2022,
                            KorakCene = "",
                            Ogranicenje = "",
                            RokZaPrijavu = new DateTime(2020, 12, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LicitacijaService.Entities.DokumentacijaZaFizickoLice", b =>
                {
                    b.HasOne("LicitacijaService.Entities.Dokumentacija", "Dokumentacija")
                        .WithMany()
                        .HasForeignKey("DokumentacijaID");
                });

            modelBuilder.Entity("LicitacijaService.Entities.DokumentacijaZaPravnoLice", b =>
                {
                    b.HasOne("LicitacijaService.Entities.Dokumentacija", "Dokumentacija")
                        .WithMany()
                        .HasForeignKey("DokumentacijaID");
                });

            modelBuilder.Entity("LicitacijaService.Entities.Licitacija", b =>
                {
                    b.HasOne("LicitacijaService.Entities.Dokumentacija", "Dokumentacija")
                        .WithMany("LicitacijaList")
                        .HasForeignKey("DokumentacijaID");
                });
#pragma warning restore 612, 618
        }
    }
}
